services:
    tatiana5.favicon.listener:
        class: tatiana5\favicon\event\listener
        arguments:
            - @config
            - @template
        tags:
            - { name: event.listener }
